import { useEffect, useMemo, useState } from 'react';
import { CRM_SEARCH_ICON } from '../../app/icons';
import { Badge, Button, ConversationWorkspace, EmptyState, PageHeader, Select, Skeleton, TabBar, Tabs, TextField, Textarea } from '../../components/ui';
import { inboxCopy } from '../../content/ja';
import type { InboxConversationDetailDto, InboxPlatform, InboxRepository, InboxStatus } from '../../features/inbox/contracts';
import { INBOX_KARTE_TABS, INBOX_PLATFORM_OPTIONS, INBOX_STATUS_TABS } from './inboxConfig';
import './InboxPreviewPage.css';

export function InboxPreviewPage({ repository }: { repository: InboxRepository }) {
  const [status, setStatus] = useState<InboxStatus>('all');
  const [platform, setPlatform] = useState<InboxPlatform>('all');
  const [query, setQuery] = useState('');
  const [details, setDetails] = useState<readonly InboxConversationDetailDto[] | null>(null);
  const [selectedId, setSelectedId] = useState('');
  const [karteTab, setKarteTab] = useState('customer');
  useEffect(() => { let active = true; void (async () => { const rows = await repository.listConversations(); const loaded = await Promise.all(rows.map((row) => repository.getConversation(row.id))); if (active) { const next = loaded.filter((value): value is InboxConversationDetailDto => value != null); setDetails(next); setSelectedId(next[0]?.conversation.id ?? ''); } })(); return () => { active = false; }; }, [repository]);
  const filtered = useMemo(() => (details ?? []).filter(({ conversation }) => (status === 'all' || conversation.status === status) && (platform === 'all' || conversation.platform === platform) && `${conversation.customerName} ${conversation.summary}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [details, platform, query, status]);
  const selected = filtered.find(({ conversation }) => conversation.id === selectedId) ?? filtered[0];
  const karteFields = selected == null ? [] : karteTab === 'customer' ? [[inboxCopy.fields.customerName, selected.karte.customerName], [inboxCopy.fields.platform, selected.karte.platform]] : karteTab === 'company' ? [[inboxCopy.fields.company, selected.karte.company], [inboxCopy.fields.status, selected.karte.status]] : [[inboxCopy.fields.nextAction, selected.karte.nextAction], [inboxCopy.fields.note, selected.karte.note]];
  return <><PageHeader eyebrow={inboxCopy.eyebrow} title={inboxCopy.title} subtitle={inboxCopy.subtitle} action={<Badge variant="info">{inboxCopy.previewBadge}</Badge>} /><section className="inbox-preview"><div className="inbox-preview__tab-row"><TabBar items={INBOX_STATUS_TABS} activeKey={status} onChange={setStatus} aria-label={inboxCopy.statusTabsLabel} /><Select aria-label={inboxCopy.platformsLabel} options={INBOX_PLATFORM_OPTIONS as { value: string; label: string }[]} value={platform} onChange={(event) => setPlatform(event.target.value as InboxPlatform)} /></div><ConversationWorkspace className="inbox-preview__workspace" listLabel={inboxCopy.listLabel} listHeader={<TextField aria-label={inboxCopy.searchLabel} placeholder={inboxCopy.searchPlaceholder} value={query} onChange={(event) => setQuery(event.target.value)} fullWidth startIcon={<CRM_SEARCH_ICON aria-hidden="true" />} />} list={details === null ? <Skeleton variant="list" rows={4} label={inboxCopy.loading} /> : filtered.length === 0 ? <EmptyState title={inboxCopy.noConversations} description={inboxCopy.previewNote} /> : <div className="inbox-preview__list">{filtered.map(({ conversation }) => <button className={`inbox-preview__row${conversation.id === selected?.conversation.id ? ' inbox-preview__row--active' : ''}`} key={conversation.id} onClick={() => setSelectedId(conversation.id)} type="button"><strong>{conversation.customerName}</strong><span>{conversation.summary}</span><small>{conversation.platform} · {conversation.updatedAt}</small></button>)}</div>} conversationLabel={inboxCopy.conversationLabel} conversationHeader={selected && <div className="inbox-preview__conversation-header"><strong>{selected.conversation.customerName}</strong><Badge variant="info" size="sm">{selected.conversation.platform}</Badge></div>} conversation={selected ? <div className="inbox-preview__messages">{selected.messages.map((message) => <article className={`inbox-preview__message inbox-preview__message--${message.sender}`} key={message.id}><p>{message.body}</p><time>{message.sentAt}</time></article>)}</div> : <EmptyState title={inboxCopy.noConversations} description={inboxCopy.previewNote} />} composer={<div className="inbox-preview__composer"><TextField aria-label={inboxCopy.composerPlaceholder} placeholder={inboxCopy.composerPlaceholder} readOnly fullWidth value="" /><Button disabled>{inboxCopy.send}</Button></div>} detailsLabel={inboxCopy.detailsLabel} detailsHeader={<Tabs items={INBOX_KARTE_TABS} activeKey={karteTab} onChange={setKarteTab} size="sm" aria-label={inboxCopy.detailTabsLabel} />} details={<div className="inbox-preview__karte">{karteFields.map(([label, value]) => label === inboxCopy.fields.note ? <Textarea key={label} label={label} readOnly value={value} /> : <TextField key={label} label={label} readOnly value={value} />)}</div>} /></section></>;
}
