import { useCallback, useEffect, useState } from 'react';
import { HashRouter, Navigate, Route, Routes } from 'react-router-dom';
import { canAccessNavigationItem, NAVIGATION_BY_ID, visibleNavigationItems, type NavigationPermissions } from './app/navigation';
import { AppShell } from './components/shell';
import { getCurrentUser, getDashboardKpis, type DashboardKpis } from './gas/client';
import { ComponentCatalogPage } from './pages/catalog/ComponentCatalogPage';
import { DashboardPage } from './pages/dashboard/DashboardPage';
import { LeadListPage } from './pages/leads/LeadListPage';
import { errorCopy } from './content/ja';
type LoadState = 'loading' | 'ready' | 'error';
export default function App() { const [state, setState] = useState<LoadState>('loading'); const [kpis, setKpis] = useState<DashboardKpis | null>(null); const [error, setError] = useState(''); const [permissions, setPermissions] = useState<NavigationPermissions | null>(null); const load = useCallback(async () => { setState('loading'); setError(''); try { setKpis(await getDashboardKpis()); setState('ready'); } catch (cause) { setError(cause instanceof Error ? cause.message : errorCopy.genericLoad); setState('error'); } }, []); const loadPermissions = useCallback(async () => { try { const user = await getCurrentUser(); setPermissions(user.success ? user.permissions : null); } catch { setPermissions(null); } }, []); useEffect(() => { void load(); void loadPermissions(); }, [load, loadPermissions]); const navigationItems = visibleNavigationItems(permissions); const canAccessLeads = canAccessNavigationItem(NAVIGATION_BY_ID.leads, permissions); return <HashRouter><AppShell navigationItems={navigationItems}><Routes><Route path={NAVIGATION_BY_ID.dashboard.hash} element={<DashboardPage kpis={kpis} state={state} error={error} onRefresh={() => void load()} />} /><Route path={NAVIGATION_BY_ID.leads.hash} element={canAccessLeads ? <LeadListPage /> : <Navigate to={NAVIGATION_BY_ID.dashboard.hash} replace />} /><Route path={NAVIGATION_BY_ID.components.hash} element={<ComponentCatalogPage />} /><Route path="*" element={<Navigate to={NAVIGATION_BY_ID.dashboard.hash} replace />} /></Routes></AppShell></HashRouter>; }
