export const authCopy = {
  loginTitle: 'ログイン',
  staffIdLabel: '担当者ID',
  staffIdPlaceholder: 'EMP-00001',
  passwordLabel: 'パスワード',
  loginButton: 'ログイン',
  loggingIn: 'ログイン中...',
  loginFailed: 'IDまたはパスワードが違います',
  logoutButton: 'ログアウト',
  changePasswordLink: 'パスワード変更',
  changePasswordTitle: 'パスワード変更',
  currentPasswordLabel: '現在のパスワード',
  newPasswordLabel: '新しいパスワード',
  confirmPasswordLabel: '新しいパスワード（確認）',
  changePasswordButton: '変更する',
  changing: '変更中...',
  changeSuccess: 'パスワードを変更しました。',
  confirmMismatch: '新しいパスワードが一致しません',
  passwordTooShort: 'パスワードは12文字以上にしてください',
  passwordUnchanged: '新しいパスワードは現在と異なるものにしてください',
  passwordMismatch: '現在のパスワードが違います',
  backToDashboard: 'ダッシュボードへ戻る',
  sessionChecking: '認証情報を確認中...',
} as const;
