export const customersCopy = {
  eyebrow: 'Customer management',
  title: '顧客一覧',
  subtitle: 'プレビュー用の顧客情報を確認できます。',
  detailTitle: '顧客詳細',
  detailSubtitle: 'プレビュー用の顧客情報を読取り専用で確認できます。',
  previewBadge: 'プレビュー',
  searchLabel: '顧客を検索',
  searchPlaceholder: '表示中の8項目から検索',
  loading: '顧客一覧を読み込んでいます。',
  detailLoading: '顧客詳細を読み込んでいます。',
  loadErrorPrefix: '顧客一覧の読み込みに失敗しました:',
  detailLoadErrorPrefix: '顧客詳細の読み込みに失敗しました:',
  retry: '再試行',
  backToList: '一覧へ戻る',
  emptyTitle: '表示できる顧客はありません',
  emptyDescription: '現在の条件に該当する顧客はありません。',
  searchEmptyTitle: '検索条件に一致する顧客はありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  detailNotFoundTitle: '顧客が見つかりません',
  detailNotFoundDescription: '指定された顧客は表示できません。',
  tableLabel: '顧客一覧',
  shippingTableLabel: '配送先一覧',
  paymentTableLabel: '支払情報一覧',
  tabsLabel: '顧客詳細の表示切替',
  tabs: { basic: '基本情報', shipping: '配送先', payment: '支払情報' },
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  columns: {
    customerName: '顧客名',
    customerType: '顧客区分',
    emailAddress: 'メールアドレス',
    country: '国',
    shippingAddressCount: '配送先件数',
    paymentProfileCount: '支払情報件数',
    status: 'ステータス',
    updatedAt: '更新日',
    recipient: '宛先',
    address: '住所',
    paymentLabel: '支払情報',
    paymentMethod: '支払方法'
  },
  shippingLabel: '区分',
  fields: {
    customerId: '顧客ID',
    customerName: '顧客名',
    customerType: '顧客区分',
    emailAddress: 'メールアドレス',
    country: '国',
    note: 'メモ'
  },
  shippingEmptyTitle: '配送先はありません',
  shippingEmptyDescription: 'このプレビュー顧客には配送先がありません。',
  paymentEmptyTitle: '支払情報はありません',
  paymentEmptyDescription: 'このプレビュー顧客には支払情報がありません。',
  previewNote: 'この画面はダミーデータのみを表示し、保存や外部接続は行いません。'
} as const;
