export const customersCopy = {
  eyebrow: 'Customer management',
  title: '顧客一覧',
  subtitle: '顧客マスタを、元リードと取引実績に紐づけて確認できます。',
  detailTitle: '顧客詳細',
  detailSubtitle: '顧客マスタと顧客IDで紐づく情報を読取り専用で確認できます。',
  searchLabel: '顧客を検索',
  searchPlaceholder: '検索',
  loading: '顧客一覧を読み込んでいます。',
  detailLoading: '顧客詳細を読み込んでいます。',
  loadErrorPrefix: '顧客一覧の読み込みに失敗しました:',
  detailLoadErrorPrefix: '顧客詳細の読み込みに失敗しました:',
  retry: '再試行',
  refresh: '更新',
  refreshing: '顧客情報を更新しています。',
  backToList: '一覧へ戻る',
  emptyTitle: '表示できる顧客はありません',
  emptyDescription: '現在の条件に該当する顧客はありません。',
  searchEmptyTitle: '検索条件に一致する顧客はありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  detailNotFoundTitle: '顧客が見つかりません',
  detailNotFoundDescription: '指定された顧客は表示できません。',
  tableLabel: '顧客一覧',
  emptyValue: '-',
  shippingTableLabel: '配送先一覧',
  paymentTableLabel: '支払情報一覧',
  tabsLabel: '顧客詳細の表示切替',
  tabs: { basic: '基本情報', shipping: '配送先', payment: '支払情報' },
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  columns: {
    customerName: '顧客名',
    emailAddress: 'メールアドレス',
    country: '国',
    phone: '電話番号',
    salesChannel: '販売形態',
    handledTitle: '取扱商材',
    salesAssigneeName: '営業担当者',
    transactionCount: '取引回数',
    transactionAmount: '取引金額',
    recipient: '宛先',
    address: '住所',
    paymentMethod: '支払方法',
    billingName: '請求名義',
    currency: '通貨',
    defaultFlag: '既定',
    activeFlag: '有効'
  },
  shippingLabel: '区分',
  fields: {
    customerId: '顧客ID',
    customerName: '顧客名',
    emailAddress: 'メールアドレス',
    country: '国',
    phone: '電話番号',
    countryCode: '国番号',
    firstTransactionDate: '初回取引日',
    registeredAt: '登録日',
    salesAssigneeName: '営業担当者',
    contactTool: '連絡ツール',
    shippingNote: '発送時メモ'
  },
  shippingEmptyTitle: '配送先はありません',
  shippingEmptyDescription: 'この顧客IDに紐づく配送先はありません。',
  paymentEmptyTitle: '支払情報はありません',
  paymentEmptyDescription: 'この顧客IDに紐づく支払先はありません。'
} as const;
