export const discordIntegrationCopy = {
  title: 'Discord連携',
  subtitle: 'Discord BotのトークンとチャンネルIDを設定します。',
  tokenSection: 'Botトークン設定',
  tokenLabel: 'Discord Botトークン',
  tokenPlaceholder: 'Botトークンを入力してください',
  saveToken: '保存',
  savingToken: '保存中...',
  tokenSaved: 'Botトークンを保存しました',
  tokenSaveError: 'Botトークンの保存に失敗しました',
  connectionSection: '接続状態',
  testConnection: '接続テスト',
  testingConnection: 'テスト中...',
  connectionStatus: {
    connected: '接続済み',
    notConnected: '未接続',
    notSet: '未設定',
  },
  botInfo: 'Bot名: {botName} (ID: {botId})',
  channelSection: '監視チャンネル設定',
  channelIdLabel: 'チャンネルID',
  channelIdPlaceholder: 'チャンネルIDを入力（例: 1234567890123456789）',
  addChannel: '追加',
  addingChannel: '追加中...',
  channelAdded: 'チャンネルIDを追加しました',
  channelAddError: 'チャンネルIDの追加に失敗しました',
  removeChannel: '削除',
  noChannels: '登録済みチャンネルはありません',
  loading: '読み込み中...',
  loadError: 'Discord連携設定の取得に失敗しました',
  retry: '再読み込み',
  permissionsChecking: '権限を確認中...',
  tokenLabelPrefix: 'トークン: ',
  connectedBot: 'Bot名: ',
  connectionSuccess: '接続テスト成功',
  notSet: '未設定',
  connectionFailed: 'Discordへの接続に失敗しました。Botトークンを確認してください。',
  testFailed: 'テストに失敗しました',
  channelDuplicate: 'このチャンネルIDは既に登録されています',
  // channel setup section
  setupSection: 'チャンネルセットアップ',
  setupStatusLoading: 'セットアップ状態を確認中...',
  setupStatusDone: 'セットアップ済み',
  setupStatusNotDone: '未セットアップ',
  setupCategoryLabel: 'カテゴリID',
  setupTicketLabel: 'ticket-startチャンネルID',
  setupButton: 'チャンネルをセットアップする',
  setupButtonRunning: 'セットアップ中...',
  setupSuccess: 'セットアップが完了しました',
  setupError: 'セットアップに失敗しました',
  setupDisabledReason: '先にBot招待を完了してください',
} as const;
