export const discordIntegrationCopy = {
  title: 'Discord連携',
  subtitle: 'Discord BotのトークンとチャンネルIDを設定します。',
  tokenSection: 'Bot認証設定',
  tokenLabel: 'Discord Botトークン',
  tokenPlaceholder: 'Botトークンを入力してください',
  saveAndConnect: '保存して接続',
  savingAndTesting: '保存して接続中...',
  saveAndConnectSuccess: '保存して接続しました。',
  savedButConnectionFailed: 'Botトークンは保存済みですが、Discordに接続できません。トークンを確認してください。',
  tokenSaveError: 'Botトークンの保存に失敗しました',
  clientIdLabel: 'Discord Application ID',
  clientIdPlaceholder: 'Application IDを入力してください',
  clientIdGuide: 'Discord Developer Portal の Application ID を入力してください。',
  saveClientId: 'Application IDを保存',
  savingClientId: 'Application IDを保存中...',
  clientIdSaveSuccess: 'Application IDを保存しました。',
  clientIdSaveError: 'Application IDの保存に失敗しました',
  connectionSection: '接続状態',
  connectionStatus: {
    connected: '接続済み',
    notConnected: '未接続',
    notSet: '未設定',
  },
  botInfo: 'Bot名: {botName} (ID: {botId})',
  channelSection: '監視チャンネル設定',
  channelIdLabel: 'チャンネルID',
  channelIdPlaceholder: 'チャンネルIDを入力（例: 1234567890123456789）',
  addChannel: '追加',
  addingChannel: '追加中...',
  channelAdded: 'チャンネルIDを追加しました',
  channelAddError: 'チャンネルIDの追加に失敗しました',
  removeChannel: '削除',
  noChannels: '登録済みチャンネルはありません',
  loading: '読み込み中...',
  loadError: 'Discord連携設定の取得に失敗しました',
  retry: '再読み込み',
  permissionsChecking: '権限を確認中...',
  tokenLabelPrefix: 'トークン: ',
  connectedBot: 'Bot名: ',
  notSet: '未設定',
  channelDuplicate: 'このチャンネルIDは既に登録されています',
  // Bot招待セクション
  inviteSection: 'Bot招待',
  inviteDescription: 'DiscordサーバーへのBotの招待と、Guild連携状態を管理します。',
  inviteButton: 'Discordサーバーに招待する',
  invitingBot: '招待URL取得中...',
  guildLinked: 'サーバー連携済み（Guild ID: ',
  guildNotLinked: '未連携',
  refreshStatus: '状態を確認する',
  refreshingStatus: '確認中...',
  inviteError: '招待URLの取得に失敗しました',
  clientIdNotSet: 'DISCORD_CLIENT_IDが未設定です。スクリプトプロパティを確認してください。',
  // channel setup section
  setupSection: 'チャンネルセットアップ',
  setupStatusLoading: 'セットアップ状態を確認中...',
  setupStatusDone: 'セットアップ済み',
  setupStatusNotDone: '未セットアップ',
  setupCategoryLabel: 'カテゴリID',
  setupTicketLabel: 'ticket-startチャンネルID',
  setupButton: 'チャンネルをセットアップする',
  setupButtonRunning: 'セットアップ中...',
  setupSuccess: 'セットアップが完了しました',
  setupError: 'セットアップに失敗しました',
  setupDisabledReason: '先にBot招待を完了してください',
} as const;
