export const leadsCopy = {
  eyebrow: 'Lead management',
  title: 'リード一覧',
  subtitle: '権限に応じてリードの表示・追加・編集ができます。',
  all: 'すべて',
  inbound: 'インバウンド',
  outbound: 'アウトバウンド',
  leadTypes: { inbound: 'インバウンド', outbound: 'アウトバウンド' },
  loading: 'リードを読み込んでいます。',
  refreshing: 'リードを更新しています。',
  refresh: '更新',
  permissionsChecking: 'リードの表示権限を確認しています。',
  loadErrorPrefix: 'リードの読み込みに失敗しました:',
  retry: '再試行',
  create: '新規リード追加',
  save: '保存',
  saving: '保存しています。',
  backToList: '一覧へ戻る',
  detailLoading: 'リード詳細を読み込んでいます。',
  detailNotFoundTitle: 'リードが見つかりません',
  detailNotFoundDescription: '指定されたリードは表示できません。',
  detailLoadErrorPrefix: 'リード詳細の読み込みに失敗しました:',
  detailLoadError: 'リード詳細を読み込めませんでした。',
  saveErrorPrefix: 'リードの保存に失敗しました:',
  customerNameRequired: '顧客名を入力してください。',
  createTitle: '新規リード追加',
  detailTitle: 'リード詳細',
  detailSubtitle: '既存リードを読取り、権限がある場合のみ明示保存できます。',
  createSubtitle: '選択中のリード種別で新規リードを作成します。',
  editingUnavailable: 'このリードは読取り専用です。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  emptyTitle: '表示できるリードはありません',
  emptyDescription: '選択中のタブに該当するデータはありません。',
  tableLabel: 'リード一覧',
  fields: { leadId: 'リードID', customerName: '顧客名', responseSpeed: '返信速度', updatedAt: 'シート更新日', csMemo: 'CSメモ', source: '流入経路', country: '国', productTitle: '取り扱いタイトル', leadType: 'リード種別', leadStatus: 'リード進捗' },
  columns: { customerName: '顧客名', responseSpeed: '返信速度', updatedAt: '更新日', csMemo: 'CSメモ', source: '流入元', country: '国', productTitle: '取り扱い商材' },
  form: { sheetName: 'リード管理', customerName: '顧客名', leadType: 'リード種別', source: '流入元', country: '国', productTitle: '取り扱い商材', responseSpeed: '返信速度', csMemo: 'CSメモ' }
} as const;
