import type { BadgeVariant } from '../../components/ui/Badge/Badge';

export const PAYMENT_STATUS_BADGE_VARIANT: Record<string, BadgeVariant> = {
  '入金済み': 'success',
  '未入金':   'warning',
  '一部入金': 'warning',
  '遅延':     'danger',
  'キャンセル': 'neutral',
  '保留':     'info',
} as const;

export const ordersCopy = {
  eyebrow: 'Order management',
  title: '請求書一覧',
  subtitle: '受注・請求書を確認できます。',
  loading: '請求書を読み込んでいます。',
  refreshing: '請求書を更新しています。',
  refresh: '更新',
  retry: '再試行',
  loadErrorPrefix: '請求書の読み込みに失敗しました:',
  searchLabel: '請求書を検索',
  searchPlaceholder: '検索',
  emptyTitle: '請求書はありません',
  emptyDescription: '受注データが見つかりませんでした。',
  searchEmptyTitle: '検索条件に一致する請求書はありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  tableLabel: '請求書一覧',
  permissionsChecking: '請求書の表示権限を確認しています。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  createOrder: '新規作成',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  columns: {
    orderId:         'オーダーID',
    customerName:    '顧客名',
    invoiceNumber:   '請求書番号',
    invoiceIssuedAt: '請求書発行日',
    paymentMethod:   '支払い方法',
    invoiceTotal:    '請求金額',
    paymentDueAt:    '支払期日',
    paymentStatus:   '支払いステータス',
  },
  editor: {
    createTitle: 'オーダー新規作成',
    createSubtitle: '受注情報を入力してオーダーを作成します。',
    masterLoadError: 'マスタデータの読み込みに失敗しました。',
    inventoryLoadError: '在庫商品の読み込みに失敗しました。',
    backToList: '一覧に戻る',
    saveOrder: '保存',
    saving: '保存中...',
    saveErrorPrefix: '保存に失敗しました:',
    saveErrorFallback: '不明なエラーが発生しました。',
    selectCustomer: '顧客を選択',
    customerPlaceholder: '顧客名または顧客IDで検索',
    customerNoResults: '顧客が見つかりません',
    shippingDestination: '配送先',
    shippingDestinationPlaceholder: '配送先を選択',
    shippingDestinationNoResults: '配送先が見つかりません',
    paymentDestination: '支払先',
    paymentDestinationPlaceholder: '支払先を選択',
    paymentDestinationNoResults: '支払先が見つかりません',
    currency: '通貨',
    shippingFee: '送料',
    duty: '関税',
    otherFee: 'その他手数料',
    discount: '値引き',
    invoiceTotal: '請求総額（自動計算）',
    paymentMethod: '決済手段',
    addLine: '明細を追加',
    removeLine: '削除',
    productName: '商品名',
    category: 'カテゴリ',
    condition: '状態',
    quantity: '数量',
    unitPrice: '単価',
    subtotal: '小計',
    lines: '明細',
    lineProduct: '商品',
    lineProductPlaceholder: '商品名で検索',
    lineProductNoResults: '商品が見つかりません',
    lineConditionPlaceholder: '商品を先に選択',
    lineConditionOptionLabel: (condition: string, quantity: number) => `${condition}（在庫: ${quantity}）`,
    lineWeight: '重量(g)',
    lineAmount: '金額',
    validation: {
      customerRequired: '顧客を選択してください。',
      shippingDestinationRequired: '配送先を選択してください。',
      paymentDestinationRequired: '支払先を選択してください。',
      linesRequired: '明細を1件以上追加してください。',
      lineQuantityRequired: (index: number) => `明細${index + 1}行目: 数量を入力してください。`,
      lineUnitPriceRequired: (index: number) => `明細${index + 1}行目: 単価を入力してください。`,
    },
    paymentMethodLabels: {
      WISE: 'Wise',
      PAYPAL: 'PayPal',
    } as Record<string, string>,
    internalNote: '内部メモ',
    internalNoteDescription: '顧客には表示されません',
    editTitle: 'オーダー編集',
    editSubtitle: 'オーダー情報を編集します。',
    amountLocked: '請求書発行済みのため金額の変更はできません',
    amountLockedDescription: '請求書が発行された後は金額系の変更ができません。',
    paymentConfirmedAt: '支払確認日',
    shippedAt: '発送日',
    trackingNumber: '運送状番号',
    shippingMethod: '発送方法',
    note: '備考',
    shippingNote: '発送時メモ',
    transactionNote: '取引備考欄',
    cancellationReason: 'キャンセル理由',
    cancellationNote: 'キャンセルメモ',
    updateOrder: '更新',
    updating: '更新中...',
    updateErrorPrefix: '更新に失敗しました:',
  },
} as const;
