import type { BadgeVariant } from '../../components/ui/Badge/Badge';

export const PAYMENT_STATUS_BADGE_VARIANT: Record<string, BadgeVariant> = {
  '入金済み': 'success',
  '未入金':   'warning',
  '一部入金': 'warning',
  '遅延':     'danger',
  'キャンセル': 'neutral',
  '保留':     'info',
} as const;

export const ordersCopy = {
  eyebrow: 'Order management',
  title: '請求書一覧',
  subtitle: '受注・請求書を確認できます。',
  loading: '請求書を読み込んでいます。',
  refreshing: '請求書を更新しています。',
  refresh: '更新',
  retry: '再試行',
  loadErrorPrefix: '請求書の読み込みに失敗しました:',
  searchLabel: '請求書を検索',
  searchPlaceholder: '検索',
  emptyTitle: '請求書はありません',
  emptyDescription: '受注データが見つかりませんでした。',
  searchEmptyTitle: '検索条件に一致する請求書はありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  tableLabel: '請求書一覧',
  permissionsChecking: '請求書の表示権限を確認しています。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  columns: {
    orderId:         'オーダーID',
    customerName:    '顧客名',
    invoiceNumber:   '請求書番号',
    invoiceIssuedAt: '請求書発行日',
    paymentMethod:   '支払い方法',
    invoiceTotal:    '請求金額',
    paymentDueAt:    '支払期日',
    paymentStatus:   '支払いステータス',
  },
  newOrder: '新規作成',
  editor: {
    createTitle:    'オーダー新規作成',
    createSubtitle: '新しい受注を登録します。',
    backToList:     '一覧に戻る',
    masterLoadError: 'マスタデータの読み込みに失敗しました。',
    inventoryLoadError: '在庫商品の読み込みに失敗しました。',
    conditionsLoadError: '在庫状態の読み込みに失敗しました。',
    saveErrorPrefix: '登録に失敗しました:',
    form: {
      customer:                  '顧客',
      customerPlaceholder:       '顧客名で検索...',
      customerNoResults:         '一致する顧客が見つかりません',
      shippingDestination:       '配送先',
      shippingDestinationPlaceholder: '配送先を選択',
      paymentDestination:        '支払先',
      paymentDestinationPlaceholder: '支払先を選択',
      currency:                  '通貨',
      shippingFee:               '送料',
      duty:                      '関税',
      otherFee:                  'その他手数料',
      discount:                  '値引き',
      paymentMethod:             '決済手段',
      paymentMethodPlaceholder:  '決済手段を選択',
      paymentTerms:              '支払サイト',
      paymentDueAt:              '支払期日',
      note:                      '備考',
      lines:                     '明細',
      addLine:                   '明細行を追加',
      removeLine:                '削除',
      lineProduct:               '商品名',
      lineProductPlaceholder:    '商品名で検索...',
      lineProductNoResults:      '一致する商品が見つかりません',
      lineCondition:             '状態',
      lineConditionPlaceholder:  '商品を先に選択',
      lineQuantity:              '数量',
      lineUnitPrice:             '単価',
      lineAmount:                '金額',
      lineWeight:                '重量(g)',
      lineConditionOptionLabel:  (condition: string, quantity: number) => `${condition}（在庫: ${quantity}）`,
    },
    save:   '登録',
    saving: '登録中...',
    validation: {
      customerRequired: '顧客を選択してください。',
      shippingRequired: '配送先を選択してください。',
      paymentRequired:  '支払先を選択してください。',
    },
  },
} as const;
