export const ordersCopy = {
  eyebrow: 'Order management',
  title: '請求書一覧',
  subtitle: '受注・請求書を確認できます。',
  loading: '請求書を読み込んでいます。',
  refreshing: '請求書を更新しています。',
  refresh: '更新',
  retry: '再試行',
  loadErrorPrefix: '請求書の読み込みに失敗しました:',
  searchLabel: '請求書を検索',
  searchPlaceholder: '5項目から検索',
  emptyTitle: '請求書はありません',
  emptyDescription: '受注データが見つかりませんでした。',
  searchEmptyTitle: '検索条件に一致する請求書はありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  tableLabel: '請求書一覧',
  permissionsChecking: '請求書の表示権限を確認しています。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  columns: {
    orderId:       'オーダーID',
    invoiceNumber: '請求書番号',
    customerId:    '顧客ID',
    status:        'ステータス',
    orderDate:     '受注日',
    currency:      '通貨',
    invoiceTotal:  '請求金額',
  },
} as const;
