export const packageMasterCopy = {
  title: '荷姿マスタ',
  subtitle: 'サイズ・重量・荷姿を登録・編集します。',
  tabSizes: 'サイズ',
  tabWeights: '重量',
  tabPackages: '荷姿',
  loading: '読み込み中…',
  loadError: '読み込みに失敗しました。',
  retry: '再試行',
  btnAddNew: '新規追加',
  btnSave: '保存',
  btnCancel: 'キャンセル',
  saving: '保存中…',
  saveSuccess: '保存しました。',
  saveError: '保存に失敗しました。',
  // Size fields
  colSizeId: 'サイズID',
  colSizeName: 'サイズ名',
  colLength: '長さ (cm)',
  colWidth: '幅 (cm)',
  colHeight: '高さ (cm)',
  colActive: '有効',
  // Weight fields
  colWeightId: '重量ID',
  colWeightName: '重量名',
  colWeightValue: '重量 (kg)',
  // Package fields
  colPackageId: '荷姿ID',
  colPackageName: '荷姿名',
  colUnit: '単位',
  colQuantity: '入数',
  colSize: 'サイズ',
  colWeightRef: '重量',
  // Misc
  inactiveLabel: '（無効）',
  noData: 'データがありません。',
  ariaTable: 'テーブル',
  ariaInlineForm: '編集フォーム',
  activeLabel: '有効',
  inactiveSelectLabel: '無効',
  selectPlaceholder: '選択してください',
} as const;
