export const productMasterCopy = {
  title: '商品マスタ',
  subtitle: '共用商品・自社商品の荷姿・品目・HTSコード・素材を設定します。',
  tabShared: '共用商品',
  tabOwn: '自社商品',
  loading: '読み込み中…',
  loadError: '読み込みに失敗しました。',
  retry: '再試行',
  search: '検索',
  searchPlaceholder: '商品名・IDで絞り込み',
  btnAddNew: '新規追加',
  btnSave: '保存',
  btnCancel: 'キャンセル',
  saving: '保存中…',
  saveSuccess: '保存しました。',
  saveError: '保存に失敗しました。',
  saveErrorPartial: '一部保存に失敗しました（失敗箇所: ',
  selectPlaceholder: '選択してください',
  noData: 'データがありません。',
  inactiveLabel: '（無効）',
  activeLabel: '有効',
  inactiveSelectLabel: '無効',
  // 共用商品 columns
  colProductId: '商品ID',
  colEnglishTitle: '商品名（英語）',
  colJapaneseTitle: '商品名（日本語）',
  colCategory: 'カテゴリ',
  colHasPackage: '荷姿割当',
  hasPackageYes: '割当あり',
  hasPackageNo: '未設定',
  // 自社商品 columns
  colOwnProductId: '自社商品ID',
  colNameEn: '商品名（英語）',
  colNameJa: '商品名（日本語）',
  colActive: '有効',
  // form labels
  labelCasePackage: 'ケース荷姿',
  labelBoxPackage: 'ボックス荷姿',
  labelPackPackage: 'パック荷姿',
  labelItem: '品目',
  labelHtsCode: 'HTSコード',
  labelMaterial: '素材',
  labelSharedProduct: '共用商品',
  labelMemo: 'メモ',
  labelOwnCategory: '大分類',
  labelOwnWork: '作品',
  labelOwnManufacturer: 'メーカー',
  perUnitSuffix: '入',
} as const;
