import type { BadgeVariant } from '../../components/ui/Badge/Badge';

export const QUOTE_STATUS_BADGE_VARIANT: Record<string, BadgeVariant> = {
  '下書き':   'neutral',
  '発行済み': 'info',
  '期限切れ': 'warning',
} as const;

export const quotesCopy = {
  eyebrow: 'Quote management',
  title: '見積もり一覧',
  subtitle: '発行済み見積もりを確認できます。',
  loading: '見積もりを読み込んでいます。',
  refreshing: '見積もりを更新しています。',
  refresh: '更新',
  retry: '再試行',
  loadErrorPrefix: '見積もりの読み込みに失敗しました:',
  searchLabel: '見積もりを検索',
  searchPlaceholder: '検索',
  emptyTitle: '見積もりはありません',
  emptyDescription: '発行済み見積もりが見つかりませんでした。',
  searchEmptyTitle: '検索条件に一致する見積もりはありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  tableLabel: '見積もり一覧',
  permissionsChecking: '見積もりの表示権限を確認しています。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  detailLoading: '見積もり詳細を読み込んでいます。',
  detailNotFoundTitle: '見積もりが見つかりません',
  detailNotFoundDescription: '指定された見積もりは表示できません。',
  detailLoadErrorPrefix: '見積もり詳細の読み込みに失敗しました:',
  newCreate: '新規作成',
  backToList: '一覧へ戻る',
  columns: {
    quoteId:      '見積もりID',
    customerName: '顧客名',
    issuedDate:   '発行日',
    expiryDate:   '有効期限',
    totalAmount:  '合計金額',
    status:       'ステータス',
  },
  detail: {
    title: '見積もり詳細',
    subtitle: '読み取り専用です。',
    leadId: 'リードID',
    customerId: '顧客ID',
    orderId: 'オーダーID',
    staffId: '担当者ID',
    issuedDate: '発行日',
    expiryDate: '有効期限',
    status: 'ステータス',
    currency: '通貨',
    exchangeRate: '為替レート',
    subtotal: '小計',
    shippingFee: '送料',
    discount: '値引き',
    totalAmount: '合計金額',
    totalAmountJpy: '合計金額（JPY）',
    note: 'メモ',
    pdfUrl: 'PDF',
    lines: '明細',
    lineColumns: {
      lineNo:      'No.',
      productName: '商品名',
      description: '説明',
      quantity:    '数量',
      unitPrice:   '単価',
      amount:      '金額',
    },
  },
  editor: {
    createTitle: '見積もり新規作成',
    detailTitle: '見積もり編集',
    createSubtitle: '新規見積もりを作成します。',
    detailSubtitle: '既存見積もりを確認・編集できます。',
    editingUnavailable: 'この見積もりは読取り専用です。',
    save: '保存',
    saving: '保存しています。',
    saveErrorPrefix: '見積もりの保存に失敗しました:',
    loadError: '見積もりを読み込めませんでした。',
    masterLoadError: 'マスタデータの読み込みに失敗しました。',
    inventoryLoadError: '商品候補の読み込みに失敗しました（手入力で続けられます）。',
    create: '新規見積もり作成',
    validation: {
      leadRequired: 'リードIDを入力してください。',
      discountInvalid: '値引きは数字のみ入力してください。',
      lineInventoryExceeded: (max: number) => `在庫数は ${max} 個までです`,
      lineInventoryError: '明細に在庫数エラーがあります。',
    },
    form: {
      leadId:          'リード',
      leadPlaceholder: '顧客名で検索...',
      leadNoResults:   '候補が見つかりません',
      currency:        '通貨',
      shippingFee:     '送料',
      discount:        '値引き',
      discountPlaceholder: '数字のみ（例: 1000）',
      note:            'メモ',
      lines:           '明細',
      addLine:         '明細行を追加',
      removeLine:      '削除',
      lineProduct:            '商品名',
      lineProductPlaceholder: '商品名で検索...',
      lineProductNoResults:   '候補が見つかりません',
      lineCondition:          '状態',
      lineConditionPlaceholder: '商品を先に選択',
      lineWeight:             '重量(g)',
      lineAmount:             '金額',
      lineConditionOptionLabel: (condition: string, quantity: number) => `${condition}（在庫: ${quantity}）`,
      lineProductName: '商品名',
      lineDescription: '説明',
      lineQuantity:    '数量',
      lineUnitPrice:   '単価',
      lineNote:        'メモ',
    },
    saveDraft:   '一時保存',
    savingDraft: '保存中...',
    issue:       '発行',
    issuing:     '発行中...',
    statusOptions: {
      draft:   '下書き',
      issued:  '発行済み',
      expired: '期限切れ',
    },
  },
} as const;
