import type { BadgeVariant } from '../../components/ui/Badge/Badge';

export const QUOTE_STATUS_BADGE_VARIANT: Record<string, BadgeVariant> = {
  '下書き':   'neutral',
  '送付済み': 'info',
  '期限切れ': 'warning',
} as const;

export const quotesCopy = {
  eyebrow: 'Quote management',
  title: '見積もり一覧',
  subtitle: '発行済み見積もりを確認できます。',
  loading: '見積もりを読み込んでいます。',
  refreshing: '見積もりを更新しています。',
  refresh: '更新',
  retry: '再試行',
  loadErrorPrefix: '見積もりの読み込みに失敗しました:',
  searchLabel: '見積もりを検索',
  searchPlaceholder: '5項目から検索',
  emptyTitle: '見積もりはありません',
  emptyDescription: '発行済み見積もりが見つかりませんでした。',
  searchEmptyTitle: '検索条件に一致する見積もりはありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  tableLabel: '見積もり一覧',
  permissionsChecking: '見積もりの表示権限を確認しています。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  detailLoading: '見積もり詳細を読み込んでいます。',
  detailNotFoundTitle: '見積もりが見つかりません',
  detailNotFoundDescription: '指定された見積もりは表示できません。',
  detailLoadErrorPrefix: '見積もり詳細の読み込みに失敗しました:',
  backToList: '一覧へ戻る',
  columns: {
    quoteId:      '見積もりID',
    customerName: '顧客名',
    issuedDate:   '発行日',
    expiryDate:   '有効期限',
    totalAmount:  '合計金額',
    status:       'ステータス',
  },
  detail: {
    title: '見積もり詳細',
    subtitle: '読み取り専用です。',
    leadId: 'リードID',
    customerId: '顧客ID',
    orderId: 'オーダーID',
    staffId: '担当者ID',
    issuedDate: '発行日',
    expiryDate: '有効期限',
    status: 'ステータス',
    currency: '通貨',
    exchangeRate: '為替レート',
    subtotal: '小計',
    shippingFee: '送料',
    discount: '値引き',
    totalAmount: '合計金額',
    totalAmountJpy: '合計金額（JPY）',
    note: 'メモ',
    pdfUrl: 'PDF',
    lines: '明細',
    lineColumns: {
      lineNo:      'No.',
      productName: '商品名',
      description: '説明',
      quantity:    '数量',
      unitPrice:   '単価',
      amount:      '金額',
    },
  },
} as const;
