import type { BadgeVariant } from '../../components/ui/Badge/Badge';

// 支払いステータスのバッジ色（/orders の PAYMENT_STATUS_BADGE_VARIANT と共通）
export const SALES_ORDER_PAYMENT_STATUS_BADGE_VARIANT: Record<string, BadgeVariant> = {
  '入金済み': 'success',
  '未入金':   'warning',
  '一部入金': 'warning',
  '遅延':     'danger',
  'キャンセル': 'neutral',
  '保留':     'info',
} as const;

export const SALES_ORDER_STATUS = {
  awaitingPayment: '支払い待ち',
  sourcing: '仕入れ中',
} as const;

export const salesOrdersCopy = {
  eyebrow: 'Sales order management',
  title: '受注管理',
  subtitle: '仕入・発送を一元管理します。',
  loading: '受注データを読み込んでいます。',
  refreshing: '受注データを更新しています。',
  refresh: '更新',
  retry: '再試行',
  loadErrorPrefix: '受注データの読み込みに失敗しました:',
  searchLabel: '受注を検索',
  searchPlaceholder: '検索',
  emptyTitle: '受注はありません',
  emptyDescription: '受注データが見つかりませんでした。',
  searchEmptyTitle: '検索条件に一致する受注はありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  tableLabel: '受注一覧',
  permissionsChecking: '受注の表示権限を確認しています。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  allTab: 'すべて',
  unknownStatus: '不明',
  statusOptionsLoading: 'タブを読み込んでいます。',
  /** 仕入れ中タブの仕入れ段階フィルタ */
  purchaseStageAll:        'すべて',
  purchaseStageNotOrdered: '未発注',
  purchaseStageOrdered:    '確認中',
  purchaseStageLabel:      '仕入れ段階',
  /** 発送待ちタブの発送段階 */
  shipmentStageLabel: {
    PREPARING:       '検品待ち',
    LABELING:        'ラベル貼付待ち',
    AWAITING_PICKUP: '集荷待ち',
    SHIPPED:         '発送済み',
    DONE:            '完了',
    NOT_STARTED:     '未着手',
  },
  /** 発送待ちタブの段階進捗ボタン文言 */
  advanceStageButton: {
    PREPARING:       '検品完了',
    LABELING:        '入力へ',
    AWAITING_PICKUP: '集荷依頼済み',
    SHIPPED:         '通知済み',
  } as Record<string, string>,
  labelShippingCountry: '発送先の国',
  labelShipmentStage:   '発送段階',
  columns: {
    orderId:          '受注番号',
    customerName:     '名前',
    shippingAddress:  '発送先',
    currency:         '通貨',
    invoiceTotal:     '金額',
    paymentDueAt:     '支払期日',
    status:           'ステータス',
    invoiceIssuedAt:  '作成日',
    invoiceNumber:    '請求書番号',
    purchaseStatus:   '仕入れ段階',
    shipmentStage:    '発送段階',
    shippingCountryJa: '発送先の国',
    paymentStatus:    '支払状況',
  },
  paymentDueBadgeOverdue:  '期限超過',
  paymentDueBadgeToday:    '本日期日',
  paymentDueBadgeTomorrow: '期日1日前',
  // 詳細ページ
  detail: {
    backToList: '一覧へ戻る',
    loading: '受注データを読み込んでいます。',
    loadError: '受注データの読み込みに失敗しました。',
    notFound: '受注が見つかりませんでした。',
    sectionBilling: '請求情報',
    sectionLines: '明細',
    sectionPurchases: '仕入れ',
    sectionShipments: '発送',
    noLines: '登録なし',
    noPurchases: '登録なし',
    noShipments: '登録なし',
    labelInvoiceNumber: '請求書番号',
    labelOrderDate: '受注日',
    labelInvoiceIssuedAt: '請求書発行日',
    labelPaymentDueAt: '支払期日',
    labelPaymentMethod: '決済手段',
    labelCurrency: '通貨',
    labelExchangeRate: '為替レート',
    labelLineTotal: '明細合計',
    labelShippingFee: '送料',
    labelDuty: '関税',
    labelDiscount: '値引き',
    labelOtherFee: 'その他手数料',
    labelInvoiceTotal: '請求総額',
    labelInvoiceTotalJpy: '円換算請求総額',
    labelPaymentStatus: '支払いステータス',
    labelNote: '備考',
    // 明細列
    colLineNumber: '行番号',
    colProductName: '商品名',
    colCategory: 'カテゴリ',
    colSku: 'SKU',
    colQuantity: '数量',
    colUnitPrice: '単価',
    colSubtotal: '小計',
    // 仕入れ列
    colSupplier: '仕入元',
    colOrderedAt: '注文日',
    colPurchaseAmount: '金額',
    colPurchaseStatus: 'ステータス',
    colPurchaseTrackingNumber: '送り状番号',
    // 発送列
    colBoxNumber: '箱番号',
    colShippingMethod: '発送方法',
    colShippedAt: '発送日',
    colShipmentTrackingNumber: '運送状番号',
    colPickupRequest: '集荷依頼',
    // 配送先・請求先
    labelShippingDestination: '配送先',
    labelPaymentDestination: '請求先',
    // サマリグリッド
    labelPaymentDueAtSummary: '支払期日',
    labelInvoiceTotalSummary: '請求総額',
    labelPaymentMethodSummary: '決済手段',
    labelInvoiceIssuedAtSummary: '請求書発行日',
    // 金額明細
    labelLineTotalDetail: '明細合計',
    labelShippingFeeSummary: '送料',
    labelDutySummary: '関税',
    labelDiscountSummary: '値引き',
    labelOtherFeeSummary: 'その他手数料',
    labelInvoiceTotalDetail: '請求総額',
    // ボタン
    btnConfirmPayment: '入金確認',
    btnAddShipment: '発送情報を追加',
    btnAddPurchase: '仕入れを追加',
    // セクション
    sectionPaymentSummary: '支払いサマリ',
    sectionDestinations: '配送先 / 請求先',
    sectionAmountDetail: '金額詳細',
    // 入金確認ダイアログ
    confirmPaymentTitle: '入金確認',
    confirmPaymentBody: (invoiceNumber: string, customerName: string, total: string) =>
      `以下の受注の入金を確認します。\n請求書番号: ${invoiceNumber}\n顧客名: ${customerName}\n請求総額: ${total}`,
    confirmPaymentConfirm: '確定',
    confirmPaymentCancel: 'キャンセル',
    confirmPaymentSuccess: '入金を確認しました。',
    confirmPaymentErrorInvalidStatus: '支払い待ち状態の受注にのみ入金確認できます。',
    confirmPaymentErrorGeneric: '入金確認に失敗しました。',
    // 仕入れフォームダイアログ
    purchaseFormTitle: '仕入れを追加',
    purchaseFormEditTitle: '仕入れを編集',
    purchaseFormConfirmTitle: '保存確認',
    purchaseFormConfirmBody: '以下の内容で保存します。よろしいですか？',
    purchaseFormConfirm: '保存する',
    purchaseFormCancel: 'キャンセル',
    purchaseFormBack: '入力に戻る',
    purchaseFormSaving: '保存中...',
    purchaseFormSaveError: '仕入れの保存に失敗しました。',
    purchaseFormStatusLoading: 'ステータスを読み込んでいます。',
    // 詳細タブ
    tabsLabel: '受注詳細タブ',
    tabBilling: '請求情報',
    tabPurchases: '仕入れ',
    tabShipments: '発送',
    // 仕入れフォームフィールドラベル
    labelPurchaseOrderedAt: '注文日',
    labelPurchaseSupplier: '仕入元',
    labelPurchaseSupplierUrl: '仕入元URL',
    labelPurchaseQuantity: '数量',
    labelPurchaseUnitPrice: '単価',
    labelPurchaseAmount: '金額',
    labelPurchaseShippingOrAgencyFee: '送料/代行費',
    labelPurchaseCarrier: '運送会社',
    labelPurchaseTrackingNumber: '送り状番号',
    labelPurchaseStatus: 'ステータス',
    labelPurchaseNote: '備考',
    // 発送フォームダイアログ
    shipmentFormTitle: '発送情報を追加',
    shipmentFormEditTitle: '発送情報を編集',
    shipmentFormConfirmTitle: '保存確認',
    shipmentFormConfirmBody: '以下の内容で保存します。よろしいですか？',
    shipmentFormConfirm: '保存する',
    shipmentFormCancel: 'キャンセル',
    shipmentFormBack: '入力に戻る',
    shipmentFormSaving: '保存中...',
    shipmentFormSaveError: '発送情報の保存に失敗しました。',
    // 発送詳細インライン表示
    shipmentDetailTitle: '発送情報',
    shipmentDetailClose: '閉じる',
    labelShipmentId: '発送ID',
    btnSaveShipment: '保存',
    // 発送フォームフィールドラベル
    labelShipmentBoxNumber: '箱番号',
    labelShipmentShippingMethod: '発送方法',
    labelShipmentShippedAt: '発送日',
    labelShipmentTrackingNumber: '運送状番号',
    labelShipmentLength: '長さ (cm)',
    labelShipmentWidth: '幅 (cm)',
    labelShipmentHeight: '高さ (cm)',
    labelShipmentWeight: '重量 (kg)',
    labelShipmentEstimatedShippingFee: '見積もり送料',
    labelShipmentInspection: '検品',
    labelShipmentPacking: '梱包',
    labelShipmentStorage: '格納',
    labelShipmentPickupRequest: '集荷依頼',
    labelShipmentNotification: '通知',
    labelShipmentNote: '備考',
    labelShipmentShippingAssigneeId: '担当者ID',
    // ファイルアップロード
    labelShipmentLabelUrl: 'ラベルURL',
    labelShipmentInvoiceUrl: 'インボイスURL',
    shipmentUploadLabelTitle: 'ラベル PDF',
    shipmentUploadInvoiceTitle: 'インボイス PDF',
    shipmentUploadDropHint: 'クリックまたはドラッグ＆ドロップ',
    shipmentUploadFileSizeHint: 'PDF のみ・最大 10 MB',
    shipmentUploadNoTrackingHint: '運送状番号を入力してからファイルをアップロードしてください',
    shipmentUploadUploading: 'アップロード中...',
    shipmentUploadError: 'アップロードに失敗しました',
    shipmentUploadViewLink: '表示する',
    // 請求情報タブ 送料概算（明細ベース）
    billingShippingFeeBtn: '送料を計算（明細から）',
    billingShippingFeeCalculating: '計算中...',
    billingShippingFeeNote: '明細の商品・コンディションから計算した概算です。梱包後の実送料は発送タブで確認できます。',
    billingShippingFeeResultTitle: '送料概算（明細ベース）',
    billingShippingFeeColCarrier: '配送会社',
    billingShippingFeeColZone: 'ゾーン',
    billingShippingFeeColWeight: '総請求重量 (kg)',
    billingShippingFeeColBoxCount: '箱数',
    billingShippingFeeColFee: '送料',
    billingShippingFeeSkippedTitle: 'スキップされた明細',
    billingShippingFeeSkippedColProduct: '商品',
    billingShippingFeeSkippedColReason: 'スキップ理由',
    billingShippingFeeNoBoxes: '計算に使用できる明細がありません（商品・コンディション・荷姿のマスタを確認してください）',
    billingShippingFeeErrorUnknown: '送料の計算に失敗しました',
    billingShippingFeeErrorOrderCountryNotResolvable: '顧客の配送先国が取得できませんでした。顧客情報を確認してください。',
    billingShippingFeeSkipReasonConditionNotFound: '商品とコンディションの組み合わせが見つかりません',
    billingShippingFeeSkipReasonConditionNotTarget: '送料計算の対象外コンディションです',
    billingShippingFeeSkipReasonConditionUnitNotApplicable: 'コンディションの単位が適用外です',
    billingShippingFeeSkipReasonProductPackageNotFound: '商品の荷姿設定がありません',
    billingShippingFeeSkipReasonPackageIdNotSet: '荷姿IDが未設定です',
    billingShippingFeeSkipReasonPackageNotFound: '荷姿が見つかりません',
    billingShippingFeeSkipReasonSizeNotFound: 'サイズが見つかりません',
    billingShippingFeeSkipReasonWeightNotFound: '重量が見つかりません',
    billingShippingFeeSkipReasonUnknown: '不明な理由でスキップされました',
    billingShippingFeeCarrierErrorZoneNotFound: '配送先ゾーンが見つかりません',
    billingShippingFeeCarrierErrorWeightExceedsMax: '最大重量 (68 kg) を超過しています',
    billingShippingFeeCarrierErrorRateNotFound: '該当する重量帯の料金が見つかりません',
    billingShippingFeeCarrierErrorInvalidBoxDimensions: '寸法の値が無効です',
    billingShippingFeeCarrierErrorUnsupportedDimRounding: '未対応の寸法丸め方式です',
    billingShippingFeeCarrierErrorNotAvailable: 'この配送会社は対象外です',
    billingShippingFeeCarrierErrorUnknown: '計算に失敗しました',
    // 送料計算
    btnCalculateShippingFee: '送料を計算',
    shippingFeeCalculating: '計算中...',
    shippingFeeNoShipments: '発送行がありません',
    shippingFeeAllRowsIncomplete: '計算に必要な寸法・重量が入力されていません（長さ・幅・高さ・重量をすべて入力してください）',
    shippingFeeIncompleteRows: '入力が不足している行があります（長さ・幅・高さ・重量がすべて入力されている行のみ計算します）',
    shippingFeeResultTitle: '送料見積結果',
    shippingFeeColCarrier: '配送会社',
    shippingFeeColZone: 'ゾーン',
    shippingFeeColWeight: '総請求重量 (kg)',
    shippingFeeColBoxCount: '箱数',
    shippingFeeColFee: '送料',
    shippingFeeErrorZoneNotFound: '配送先ゾーンが見つかりません',
    shippingFeeErrorWeightExceedsMax: '最大重量 (68 kg) を超過しています',
    shippingFeeErrorRateNotFound: '該当する重量帯の料金が見つかりません',
    shippingFeeErrorInvalidBoxDimensions: '寸法の値が無効です',
    shippingFeeErrorUnsupportedDimRounding: '未対応の寸法丸め方式です',
    shippingFeeErrorNotAvailable: 'この配送会社は対象外です',
    shippingFeeErrorMissingCountryCode: '配送先の国が登録されていません。受注の配送先を確認してください。',
    shippingFeeErrorUnknown: '計算に失敗しました',
  },
} as const;
