import type { BadgeVariant } from '../../components/ui/Badge/Badge';

// 支払いステータスのバッジ色（/orders の PAYMENT_STATUS_BADGE_VARIANT と共通）
export const SALES_ORDER_PAYMENT_STATUS_BADGE_VARIANT: Record<string, BadgeVariant> = {
  '入金済み': 'success',
  '未入金':   'warning',
  '一部入金': 'warning',
  '遅延':     'danger',
  'キャンセル': 'neutral',
  '保留':     'info',
} as const;

export const salesOrdersCopy = {
  eyebrow: 'Sales order management',
  title: '受注管理',
  subtitle: '仕入・発送を一元管理します。',
  loading: '受注データを読み込んでいます。',
  refreshing: '受注データを更新しています。',
  refresh: '更新',
  retry: '再試行',
  loadErrorPrefix: '受注データの読み込みに失敗しました:',
  searchLabel: '受注を検索',
  searchPlaceholder: '検索',
  emptyTitle: '受注はありません',
  emptyDescription: '受注データが見つかりませんでした。',
  searchEmptyTitle: '検索条件に一致する受注はありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  tableLabel: '受注一覧',
  permissionsChecking: '受注の表示権限を確認しています。',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  allTab: 'すべて',
  unknownStatus: '不明',
  statusOptionsLoading: 'タブを読み込んでいます。',
  columns: {
    orderId:         '受注番号',
    customerName:    '名前',
    shippingAddress: '発送先',
    currency:        '通貨',
    invoiceTotal:    '金額',
    paymentDueAt:    '支払期日',
    status:          'ステータス',
    invoiceIssuedAt: '作成日',
  },
  paymentDueBadgeOverdue:  '期限超過',
  paymentDueBadgeToday:    '本日期日',
  paymentDueBadgeTomorrow: '期日1日前',
  // 詳細ページ
  detail: {
    backToList: '一覧へ戻る',
    loading: '受注データを読み込んでいます。',
    loadError: '受注データの読み込みに失敗しました。',
    notFound: '受注が見つかりませんでした。',
    sectionBilling: '請求情報',
    sectionLines: '明細',
    sectionPurchases: '仕入れ',
    sectionShipments: '発送',
    noLines: '登録なし',
    noPurchases: '登録なし',
    noShipments: '登録なし',
    labelInvoiceNumber: '請求書番号',
    labelOrderDate: '受注日',
    labelInvoiceIssuedAt: '請求書発行日',
    labelPaymentDueAt: '支払期日',
    labelPaymentMethod: '決済手段',
    labelCurrency: '通貨',
    labelExchangeRate: '為替レート',
    labelLineTotal: '明細合計',
    labelShippingFee: '送料',
    labelDuty: '関税',
    labelDiscount: '値引き',
    labelOtherFee: 'その他手数料',
    labelInvoiceTotal: '請求総額',
    labelInvoiceTotalJpy: '円換算請求総額',
    labelPaymentStatus: '支払いステータス',
    labelNote: '備考',
    // 明細列
    colLineNumber: '行番号',
    colProductName: '商品名',
    colCategory: 'カテゴリ',
    colSku: 'SKU',
    colQuantity: '数量',
    colUnitPrice: '単価',
    colSubtotal: '小計',
    // 仕入れ列
    colSupplier: '仕入元',
    colOrderedAt: '注文日',
    colPurchaseAmount: '金額',
    colPurchaseStatus: 'ステータス',
    colPurchaseTrackingNumber: '送り状番号',
    // 発送列
    colBoxNumber: '箱番号',
    colShippingMethod: '発送方法',
    colShippedAt: '発送日',
    colShipmentTrackingNumber: '運送状番号',
    colPickupRequest: '集荷依頼',
  },
} as const;
