export const staffCopy = {
  eyebrow: 'Staff management',
  title: 'スタッフ一覧',
  subtitle: '担当者マスタに登録されているスタッフを確認できます。',
  detailTitle: 'スタッフ詳細',
  detailSubtitle: 'スタッフの詳細情報を読取り専用で確認できます。',
  searchLabel: 'スタッフを検索',
  searchPlaceholder: '検索',
  loading: 'スタッフ一覧を読み込んでいます。',
  detailLoading: 'スタッフ詳細を読み込んでいます。',
  loadErrorPrefix: 'スタッフ一覧の読み込みに失敗しました:',
  detailLoadErrorPrefix: 'スタッフ詳細の読み込みに失敗しました:',
  retry: '再試行',
  backToList: '一覧へ戻る',
  emptyTitle: '表示できるスタッフはありません',
  emptyDescription: '現在の条件に該当するスタッフはありません。',
  searchEmptyTitle: '検索条件に一致するスタッフはありません',
  searchEmptyDescription: '検索語を変更またはクリアしてください。',
  detailNotFoundTitle: 'スタッフが見つかりません',
  detailNotFoundDescription: '指定されたスタッフは表示できません。',
  tableLabel: 'スタッフ一覧',
  emptyValue: '-',
  sortAscending: '昇順',
  sortDescending: '降順',
  sortNone: '未選択',
  sortLabel: (label: string, direction: string) => `${label}を${direction}で並べ替え`,
  columns: {
    staffId: 'スタッフID',
    fullNameJa: '氏名',
    role: '役割',
    status: 'ステータス',
    email: 'メール',
    discordId: 'Discord ID'
  },
  fields: {
    staffId: 'スタッフID',
    lastNameJa: '苗字',
    firstNameJa: '名前',
    fullNameJa: '氏名',
    lastNameKana: '苗字（ふりがな）',
    firstNameKana: '名前（ふりがな）',
    lastNameEn: '苗字（英語）',
    firstNameEn: '名前（英語）',
    email: 'メール',
    discordId: 'Discord ID',
    role: '役割',
    status: 'ステータス'
  }
} as const;
