import type { InboxConversationDetailDto, InboxRepository } from './contracts';
const conversations: readonly InboxConversationDetailDto[] = [
  { conversation: { id: 'preview-inbox-alpha', customerName: 'Preview Atlas', platform: 'messenger', status: 'lead', summary: 'Preview lead conversation', updatedAt: '10:20', unread: true }, messages: [{ id: 'alpha-1', sender: 'customer', body: 'Preview message from customer.', sentAt: '10:12' }, { id: 'alpha-2', sender: 'operator', body: 'Preview reply from operator.', sentAt: '10:20' }], karte: { customerName: 'Preview Atlas', company: 'Preview Company A', platform: 'Messenger', status: 'Lead', nextAction: 'Preview follow-up', note: 'Preview note only.' } },
  { conversation: { id: 'preview-inbox-bravo', customerName: 'Preview Bravo', platform: 'instagram', status: 'deal', summary: 'Preview deal conversation', updatedAt: '09:45', unread: false }, messages: [{ id: 'bravo-1', sender: 'customer', body: 'Preview deal message.', sentAt: '09:45' }], karte: { customerName: 'Preview Bravo', company: 'Preview Company B', platform: 'Instagram', status: 'Deal', nextAction: 'Preview qualification', note: 'Preview note only.' } },
  { conversation: { id: 'preview-inbox-charlie', customerName: 'Preview Charlie', platform: 'discord', status: 'existing', summary: 'Preview existing customer conversation', updatedAt: 'Yesterday', unread: false }, messages: [{ id: 'charlie-1', sender: 'operator', body: 'Preview existing customer message.', sentAt: 'Yesterday' }], karte: { customerName: 'Preview Charlie', company: 'Preview Company C', platform: 'Discord', status: 'Existing customer', nextAction: 'Preview account review', note: 'Preview note only.' } },
  { conversation: { id: 'preview-inbox-delta', customerName: 'Preview Delta', platform: 'messenger', status: 'followup', summary: 'Preview follow-up conversation', updatedAt: 'Monday', unread: true }, messages: [{ id: 'delta-1', sender: 'customer', body: 'Preview follow-up message.', sentAt: 'Monday' }], karte: { customerName: 'Preview Delta', company: 'Preview Company D', platform: 'Messenger', status: 'Follow-up', nextAction: 'Preview follow-up', note: 'Preview note only.' } },
  { conversation: { id: 'preview-inbox-echo', customerName: 'Preview Echo', platform: 'instagram', status: 'archive', summary: 'Preview archived conversation', updatedAt: 'Last week', unread: false }, messages: [{ id: 'echo-1', sender: 'operator', body: 'Preview archived message.', sentAt: 'Last week' }], karte: { customerName: 'Preview Echo', company: 'Preview Company E', platform: 'Instagram', status: 'Archived', nextAction: 'Preview archive review', note: 'Preview note only.' } }
];
export const inboxPreviewRepository: InboxRepository = { async listConversations() { await Promise.resolve(); return conversations.map(({ conversation }) => conversation); }, async getConversation(id) { await Promise.resolve(); return conversations.find(({ conversation }) => conversation.id === id) ?? null; } };
